## Mark Shust's Docker Configuration for Magento
## (https://github.com/markshust/docker-magento)
##
## Version 47.0.1

## To use SSH, see https://github.com/markshust/docker-magento#ssh
## Linux users, see https://github.com/markshust/docker-magento#linux

## If you changed the default Docker network, you may need to replace
## 172.17.0.1 in this file with the result of:
## docker network inspect bridge --format='{{(index .IPAM.Config 0).Gateway}}'

services:
  app:
    image: markoshust/magento-nginx:1.24-0
    volumes: &appvolumes
      - ~/.composer:/var/www/.composer:cached
      - ~/.ssh/id_rsa:/var/www/.ssh/id_rsa:cached
      - ~/.ssh/known_hosts:/var/www/.ssh/known_hosts:cached
      - appdata-green:/var/www/html
      - sockdata-green:/sock
      - ssldata-green:/etc/nginx/certs
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.green.tls=true"
      - "traefik.http.routers.green.entrypoints=websecure"
      - "traefik.http.services.green.loadbalancer.server.port=8443"
      - "traefik.http.services.green.loadbalancer.server.scheme=https"
    networks:
    - green-network

  phpfpm:
    image: markoshust/magento-php:8.3-fpm-2
    volumes: *appvolumes
    env_file: env/phpfpm.env
    #extra_hosts: *appextrahosts
    networks:
      - green-network

  db:
    image: mariadb:10.6
    command:
      --max_allowed_packet=64M
      --optimizer_use_condition_selectivity=1
      --optimizer_switch="rowid_filter=off"
    labels:
      - "traefik.enable=true"
      - "traefik.tcp.routers.db-green.rule=HostSNI(`*`)"
      - "traefik.tcp.services.db-green.loadbalancer.server.port=3306"
      - "traefik.tcp.routers.db-green.entrypoints=mysql"
    env_file: env/db.env
    volumes:
      - dbdata-green:/var/lib/mysql
    networks:
      - green-network

  ## If you wish to use MySQL, comment out the mariadb db image above and
  ## uncomment this block.
  #db:
  #  image: mysql:8.0
  #  command:
  #    --max_allowed_packet=64M
  #    --optimizer_use_condition_selectivity=1
  #    --optimizer_switch="rowid_filter=off"
  #  ports:
  #    - "3306:3306"
  #  env_file: env/db.env
  #  volumes:
  #    - dbdata:/var/lib/mysql

  redis:
    image: redis:7.2-alpine
    networks:
      - green-network

  opensearch:
    image: markoshust/magento-opensearch:2.12-0
    env_file: env/opensearch.env
    environment:
      - "discovery.type=single-node"
      - "cluster.routing.allocation.disk.threshold_enabled=false"
      - "index.blocks.read_only_allow_delete"
    networks:
      - green-network

  rabbitmq:
    image: markoshust/magento-rabbitmq:3.12-0
    volumes:
      - rabbitmqdata-green:/var/lib/rabbitmq
    env_file: env/rabbitmq.env
    networks:
      - green-network

  mailcatcher:
    image: sj26/mailcatcher
    labels:
      - "traefik.enable=true"
      - "traefik.docker.network=green-network"
      - "traefik.http.routers.green_mailcatcher.tls=true"
      - "traefik.http.routers.green_mailcatcher.entrypoints=websecure"
      - "traefik.http.routers.green_mailcatcher.service=green_mailcatcher"
      - "traefik.http.services.green_mailcatcher.loadbalancer.server.port=1080"
    networks:
      - green-network

volumes:
  appdata-green:
  dbdata-green:
  rabbitmqdata-green:
  sockdata-green:
  ssldata-green:


networks:
  green-network:
    external: true